version: '3.4'

services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__HealthcareAppDatabase=Host=db;Database=HealthcareAppDb;Username=postgres;Password=<password>

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=HealthcareAppDb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
